apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Values.name | default "hello"  }}
spec:
  selector:
    matchLabels:
      app: {{  .Values.name | default "hello"  }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{  .Values.name | default "hello"  }}
    spec:
      containers:
        - name: hello
          image: ldomotor/hello:{{  .Values.dockerImageVersion | default "latest"  }}
