pipeline {

  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
            - name: helm-agent
              image: ldomotor/jenkins-helm-agent:alpha
              imagePullPolicy: Always
              command: ["tail", "-f", "/dev/null"]
              volumeMounts:
                - name: docker
                  mountPath: /var/run/docker.sock
          volumes:
            - name: docker
              hostPath:
                path: /var/run/docker.sock
        '''
    }
  }

  parameters {
    string(name: 'branchToBuild', defaultValue: 'main', description: 'Branch to build')
    booleanParam(name: 'runDefault', defaultValue: true, description: 'If this checked: Hello World!')
    string(name: 'userNameToPrint', defaultValue: '', description: 'If this specified and runDefault is false: Hello <NAME>!')
    string(name: 'dockerImageVersion', defaultValue: 'latest', description: 'Docker image\'s version to deploy')
    choice(name: 'clusterToDeploy', choices: ['docker-desktop'], description: 'Kubernetes cluster\'s name to deploy')
  }
  
  environment {
    def gitRepo = 'https://github.com/lugosidomotor/devops-assessment.git'
    def dockerImage = 'hello'
    def dockerRepository = 'ldomotor'
    def gitCommit = ''
    def shortCommit = ''
  }

  stages {      
    stage('Checkout Source') {
      steps {
        script {
          git branch: params.branchToBuild, url: gitRepo
          gitCommit = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
          shortCommit = gitCommit.take(6)
        }
      }
    }

    stage('Docker Build') {
      steps {
        script {
          container('helm-agent') {
            dockerTag = "${env.BUILD_NUMBER}-${shortCommit}"
            sh """
              set -x
              if [ ${params.runDefault} = true ]; then
                docker build -t ${env.dockerRepository}/${env.dockerImage}:${dockerTag} -t ${env.dockerRepository}/${env.dockerImage}:latest .
              else
                docker build --build-arg username='${params.userNameToPrint}' -t ${env.dockerRepository}/${env.dockerImage}:${dockerTag} -t ${env.dockerRepository}/${env.dockerImage}:latest .
              fi
            """
          }
        }
      }
    }

    stage('Docker Login') {
      steps {
          container('helm-agent') {
            withCredentials([usernamePassword(credentialsId: 'dockerHub', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
              sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
          }
        }
      }
    }

    stage('Docker Push') {
      steps {
        container('helm-agent') {
          sh "docker image push --all-tags ${env.dockerRepository}/${env.dockerImage}"
        }
      }
    }
    
    stage('Helm Deploy') {
      steps {
        container('helm-agent') {
          withCredentials([file(credentialsId: "${params.clusterToDeploy}-kubeconfig", variable: 'kubeconfig')]) {
            sh "cp \$kubeconfig /tmp/config"
            sh "export 'KUBECONFIG=/tmp/config' && helm upgrade --install --force --set dockerImageVersion=${params.dockerImageVersion} hello ./hello"
          }
        }
      }
    }
  }

post {
  always {
    script {
      currentBuild.description = "Docker image: ${env.dockerRepository}/${env.dockerImage}:${dockerTag}"
    }
  }
}
}
